[package]
name = "tytodb-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
tytodb-client = {version="0.1.2", features=["thread"], path="/home/theo/Documents/coding/TytoDB-RustClient"}
